language: node_js

node_js:
  - 17
vm:
  size: large
cache:
  directories:
    - ~/.cache/yarn
install:
  - yarn install --frozen-lockfile

env:
  global:
    - NODE_ENV=CI
    - RELEASE_NAME=dev
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn lint
before_deploy:
  - git config --global user.email "services@iprojects.ru"
  - git config --global user.name "sendsay-cat"
deploy:
  - provider: script
    skip_cleanup: true
    script: bin/deploy.sh
    on:
      branch: stable
before_script: export NODE_OPTIONS=â€“max_old_space_size=4096
